#%RAML 0.8
title: Conference API
baseUri: http://localhost:3000/api/{version}
version: v0.1
mediaType: application/json
/events:
  displayName: List of events
  description: This resource represents public events which have a name, description, location and start and ending time.  You can query the list of all events, post new events, and request details of a particular event.
  options:
    responses:
      200:
        headers:
          Access-Control-Allow-Origin:
            default: |
              *
          Access-Control-Allow-Methods:
            default: |
              OPTIONS GET POST
          Access-Control-Allow-Headers:
            default: |
              Content-Type
  post:
    description: Create new event
    responses:
      400:
        description: Failure
        headers:
          Access-Control-Allow-Origin:
            default: |
              *
      201:
        description: Success
        headers:
          Access-Control-Allow-Origin:
            default: |
              *
          Access-Control-Allow-Methods:
            default: |
              GET POST
        body:
          application/json:
            example: |
              { "message" : "Event created" }
    body:
      application/x-www-form-urlencoded:
        formParameters:
          id:
            description: Event name.
            type: integer
            required: true
          name:
            description: Event name.
            type: string
            required: true
          description:
            description: Event description.
            type: string
          location:
            description: Event location.
            type: string
          starts_at:
            description: Event start time.
            type: string
            required: true
          ends_at:
            description: Event end time.
            type: string
      application/json:
        schema: |
          {
            "$schema": "http://json-schema.org/draft-04/schema",
            "type" : "object",
            "properties" : {
                "id" : { "type" : "number" },
                "name" : { "type" : "string", "minLength":1 },
                "description" : { "type" : "string" },
                "location" : { "type" : "string" },
                "starts_at" : { "type" : "string" },
                "ends_at" : { "type" : "string" }
            }
          }
        example: |  
          { 
            "id":0,
            "name":"APICon SF", 
            "description":"APIcon is a 3-day interactive conference for app developers, existing public API providers, and those currently developing an API strategy.\nFrom May 27-29, 450+ stakeholders in the API economy will gather at the Hilton San Francisco Union Square to learn, create, ideate, and debate while advancing the overall interests of the API economy and all of its constituents. - See more at: http://www.apiconsf.com/#sthash.prwopBLX.dpuf", 
            "location":"750 Kearny St, San Francisco, CA 94108", 
            "starts_at":"2014-05-27",
            "ends_at":"2014-05-29"
          }
  get:
    description: Show collection of Events
    queryParameters:
      sort_order:
        default: "desc"
        example: "asc"
        description: Determines (asc)ending or (desc)ending order of Groups
    responses:
      200:
        description: Success
        headers:
          Access-Control-Allow-Origin:
            default: |
              *
        body:
          application/json:
            example: |
              [ 
                { 
                  "id":0,
                  "name":"APICon SF", 
                  "description":"APIcon is a 3-day interactive conference for app developers, existing public API providers, and those currently developing an API strategy.\nFrom May 27-29, 450+ stakeholders in the API economy will gather at the Hilton San Francisco Union Square to learn, create, ideate, and debate while advancing the overall interests of the API economy and all of its constituents. - See more at: http://www.apiconsf.com/#sthash.prwopBLX.dpuf", 
                  "location":"750 Kearny St, San Francisco, CA 94108", 
                  "starts_at":"2014-05-27",
                  "ends_at":"2014-05-29"
                },
                { 
                  "id":1,
                  "name":"APICon SF 2015", 
                  "description":"APIcon is a 5-day interactive conference for app developers, existing public API providers, and those currently developing an API strategy.\nFrom May 27-29, 1000+ stakeholders in the API economy will gather at the Hilton San Francisco Union Square to learn, create, ideate, and debate while advancing the overall interests of the API economy and all of its constituents. - See more at: http://www.apiconsf2015.com/not-a-real-url", 
                  "location":"750 Kearny St, San Francisco, CA 94108", 
                  "starts_at":"2015-05-27",
                  "ends_at":"2015-05-29"
                }
              ]
          application/xml:
            example: |
              <?xml version="1.0" encoding="UTF-8"?>
              <event>
                 <list>
                    <description>APIcon is a 3-day interactive conference for app developers, existing public API providers, and those currently developing an API strategy. From May 27-29, 450+ stakeholders in the API economy will gather at the Hilton San Francisco Union Square to learn, create, ideate, and debate while advancing the overall interests of the API economy and all of its constituents. - See more at: http://www.apiconsf.com/#sthash.prwopBLX.dpuf</description>
                    <ends_at>2014-05-29</ends_at>
                    <id>0</id>
                    <location>750 Kearny St, San Francisco, CA 94108</location>
                    <name>APICon SF</name>
                    <starts_at>2014-05-27</starts_at>
                 </list>
                 <list>
                    <description>APIcon is a 5-day interactive conference for app developers, existing public API providers, and those currently developing an API strategy. From May 27-29, 1000+ stakeholders in the API economy will gather at the Hilton San Francisco Union Square to learn, create, ideate, and debate while advancing the overall interests of the API economy and all of its constituents. - See more at: http://www.apiconsf2015.com/not-a-real-url</description>
                    <ends_at>2015-05-29</ends_at>
                    <id>1</id>
                    <location>750 Kearny St, San Francisco, CA 94108</location>
                    <name>APICon SF 2015</name>
                    <starts_at>2015-05-27</starts_at>
                 </list>
              </event>
          
  /{eid}:
    displayName: Individual event
    uriParameters:
      eid:
        displayName: Event Id
        type: number
        minimum: 0
    get:
      description: Details of a particular event
      responses:
        200:
          description: Success
          headers:
            Access-Control-Allow-Origin:
              default: |
                *
          body:
            application/json:
              example: |
                { 
                  "id":0,
                  "name":"APICon SF", 
                  "description":"APIcon is a 3-day interactive conference for app developers, existing public API providers, and those currently developing an API strategy.\nFrom May 27-29, 450+ stakeholders in the API economy will gather at the Hilton San Francisco Union Square to learn, create, ideate, and debate while advancing the overall interests of the API economy and all of its constituents. - See more at: http://www.apiconsf.com/#sthash.prwopBLX.dpuf", 
                  "location":"750 Kearny St, San Francisco, CA 94108", 
                  "starts_at":"2014-05-27",
                  "ends_at":"2014-05-29"
                }
            application/xml:
              example: |
                <?xml version="1.0" encoding="UTF-8"?>
                <event>
                   <description>APIcon is a 3-day interactive conference for app developers, existing public API providers, and those currently developing an API strategy. From May 27-29, 450+ stakeholders in the API economy will gather at the Hilton San Francisco Union Square to learn, create, ideate, and debate while advancing the overall interests of the API economy and all of its constituents. - See more at: http://www.apiconsf.com/#sthash.prwopBLX.dpuf</description>
                   <ends_at>2014-05-29</ends_at>
                   <id>2</id>
                   <location>750 Kearny St, San Francisco, CA 94108</location>
                   <name>APICon SF</name>
                   <starts_at>2014-05-27</starts_at>
                </event>
        404:
          description: Group not found.
          headers:
            Access-Control-Allow-Origin:
              default: |
                *
          body:
            application/json:
              example: |
                { "error" : "resource not found" }
    /sessions:
      displayName: Sessions list. This resource represents event sessions which have a name, description, organizers, location and start and ending time.
      get:
        description: Lists sessions for the associated event.
        responses:
          200:
            description: Success
            headers:
              Access-Control-Allow-Origin:
                default: |
                  *
            body:
              application/json:
                example: | 
                  [ 
                    { 
                      "id":1,
                      "name":"From Idea to API in Half a Day",
                      "organizers" : [ "Dave Nielsen, Platform D, Inc.", "Gopi Soundarrajan, Mulesoft"],
                      "location" : "Union Square Room",
                      "starts_at":"03:50",
                      "ends_at":"04:45"
                    },
                    { 
                      "id":2,
                      "starts_at":"TBD",
                      "ends_at":"TBD",
                      "name":"3scale - Tips To Rock At Hackathons",
                      "organizers" : [ "Nicolas Grenié, 3scale", "Vanessa Ramos, 3scale"],
                      "location" : "Union Square Room"
                    },
                    { 
                      "id":3,
                      "starts_at":"03:50",
                      "ends_at":"04:45",
                      "name":"Nexmo - Solve Real-World Problems with SMS",
                      "organizers" : [ "Tim Lytle, Nexmo"],
                      "location" : "Union Square Room"
                    }
                  ]
              application/xml:
                example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <sessions>
                     <list>
                        <ends_at>04:45</ends_at>
                        <id>1</id>
                        <location>Union Square Room</location>
                        <name>From Idea to API in Half a Day</name>
                        <organizers>
                           <list>Dave Nielsen, Platform D, Inc.</list>
                           <list>Gopi Soundarrajan, Mulesoft</list>
                        </organizers>
                        <starts_at>03:50</starts_at>
                     </list>
                     <list>
                        <ends_at>TBD</ends_at>
                        <id>2</id>
                        <location>Union Square Room</location>
                        <name>3scale - Tips To Rock At Hackathons</name>
                        <organizers>
                           <list>Nicolas Grenié, 3scale</list>
                           <list>Vanessa Ramos, 3scale</list>
                        </organizers>
                        <starts_at>TBD</starts_at>
                     </list>
                     <list>
                        <ends_at>04:45</ends_at>
                        <id>3</id>
                        <location>Union Square Room</location>
                        <name>Nexmo - Solve Real-World Problems with SMS</name>
                        <organizers>
                           <list>Tim Lytle, Nexmo</list>
                        </organizers>
                        <starts_at>03:50</starts_at>
                     </list>
                  </sessions>
      /{sid}:
        displayName: Session details
        uriParameters:
          sid:
            displayName: Session id number
            type: number
            minimum: 0
        get:
          description: Retrieve session details
          responses:
            200:
              description: Success
              headers:
                Access-Control-Allow-Origin:
                  example: |
                    *
              body:
                application/json:
                  example: | 
                    { 
                      "id":1,
                      "name":"From Idea to API in Half a Day",
                      "organizers" : [ "Dave Nielsen, Platform D, Inc.", "Gopi Soundarrajan, Mulesoft"],
                      "location" : "Union Square Room",
                      "starts_at":"03:50",
                      "ends_at":"04:45"
                    }
                application/xml:
                  example:
                    <?xml version="1.0" encoding="UTF-8"?>
                    <session>
                       <ends_at>04:45</ends_at>
                       <id>1</id>
                       <location>Union Square Room</location>
                       <name>From Idea to API in Half a Day</name>
                       <organizers>
                          <list>Dave Nielsen, Platform D, Inc.</list>
                          <list>Gopi Soundarrajan, Mulesoft</list>
                       </organizers>
                       <starts_at>03:50</starts_at>
                    </session>
