#%RAML 0.8
title: Workshop Demo API
version: v0.1
#baseUri: http://<<your ip>>/api/{version}
baseUri: http://mocksvc.mulesoft.com/mocks/0af0b48e-88f9-47ac-808f-566555e0043a/api/{version}
protocols: [HTTP]
schemas:
- Group: !include group.json
/groups:
  displayName: Groups
  post:
    description: Create new group
    headers:
      Access-Control-Allow-Origin:
        example: |
          *
    body:
      application/json:
        schema: Group
        example: |  
          { 
            "id":20,
            "name":"CloudCamp", 
            "slug":"cloudcamp", 
            "category":"topic", 
            "parentGroup_id":null 
          }
  get:
    description: Show collection of Groups
    responses:
      200:
        description: Success
        headers:
          Access-Control-Allow-Origin:
            example: |
              *
        body:
          application/json:
            example: | 
              [ 
                { 
                  "id":20,
                  "name":"CloudCamp", 
                  "slug":"cloudcamp", 
                  "category":"topic", 
                  "parentGroup_id":null 
                },
                { 
                    "id":21, 
                    "name":"BigDataCamp", 
                    "slug":"bigdatacamp", 
                    "category":"topic", 
                    "parentGroup_id":null 
                }
              ]
  /{gid}:
    displayName: Group
    uriParameters:
      gid:
        displayName: Group Id
        type: number
        minimum: 0
    get:
      description: Details of a particular group
      responses:
        200:
          description: Success
          headers:
            Access-Control-Allow-Origin:
              example: |
                *
          body:
            application/json:
              example: |  
                { 
                  "id":20,
                  "name":"CloudCamp", 
                  "slug":"cloudcamp", 
                  "category":"topic", 
                  "parentGroup_id":null 
                }
    
